FROM gradle:8.1.1-jdk17-alpine AS build
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src
RUN /home/gradle/src/gradlew newtransfer:transfer-07-provider-push-http:provider-push-http-backend-service:build

FROM eclipse-temurin:17-jre-alpine

COPY --from=build ./home/gradle/src/newtransfer/transfer-07-provider-push-http/provider-push-http-backend-service/build/libs/provider-push-http-backend-service.jar app.jar

ENTRYPOINT [ "sh", "-c", "exec java $JVM_ARGS -jar app.jar"]
