version: "3.8"

services:

  connector-1:
    container_name: connector-1
    build:
      context: ../
      dockerfile: Dockerfile_consumer
    volumes:
      - ./:/open-telemetry
    ports:
      - "8181:8181"
      - "8182:8182"
      - "8282:8282"
      - "8183:8183"
      - "8184:8184"
      - "8185:8185"
    environment:
      OTEL_SERVICE_NAME: connector-1
      OTEL_TRACES_EXPORTER: jaeger
      OTEL_JAVAAGENT_EXTENSIONS: opentelemetry-exporter-jaeger.jar
      OTEL_EXPORTER_JAEGER_ENDPOINT: http://jaeger:14250
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318
      OTEL_METRICS_EXPORTER: prometheus
      OTEL_LOGS_EXPORTER: none
      WEDC_BLOCKCHAIN_INTERFACE_URL: "http://edc-interface-1:3000"
      IDS_WEBHOOK_ADDRESS: "http://connector-1:8282"
      WEB_HTTP_PORT: "8181"
      WEB_HTTP_PATH: "/api"
      WEB_HTTP_PROTOCOL_PORT: 8184
      WEB_HTTP_PROTOCOL_PATH: "/protocol"
      WEB_HTTP_MANAGEMENT_PORT: "8182"
      WEB_HTTP_MANAGEMENT_PATH: "/management"
      WEB_HTTP_CONTROL_PORT: 8183
      WEB_HTTP_CONTROL_PATH: "/control"
      WEB_HTTP_PUBLIC_PORT: 8185
      WEB_HTTP_PUBLIC_PATH: "/public"
      EDC_API_AUTH_KEY: "password"
      EDC_WEB_REST_CORS_ENABLED: "true"
      EDC_WEB_REST_CORS_HEADERS: "*"
      EDC_WEB_REST_CORS_ORIGINS: "*"
      EDC_WEB_REST_CORS_METHODS: "GET, POST, DELETE, PUT, OPTIONS"
      EDC_RECEIVER_HTTP_ENDPOINT: "http://http-push-backend-services:4000/receiver/urn:connector:provider/callback"
      EDC_DATAPLACE_TOKEN_VALIDATION_ENDPOINT: "http://connector-1:8183/control/token"
      EDC_HOSTNAME: "connector-1"
      EDC_DSP_CALLBACK_ADDRESS: "http://connector-1:8184/protocol"
    entrypoint: java
      -javaagent:/opentelemetry-javaagent.jar
      -Djava.util.logging.config.file=/open-telemetry/resources/logging.properties
      -Dedc.fs.config=config.properties
      -Dedc.keystore=cert.pfx
      -Dedc.keystore.password=123456
      -Dedc.vault=vault.properties
      -jar app.jar

  connector-2:
    container_name: connector-2
    build:
      context: ../
      dockerfile: Dockerfile_provider
    volumes:
      - ./:/open-telemetry
    ports:
      - "9191:9191"
      - "9192:9192"
      - "9292:9292"
      - "9193:9193"
      - "9194:9194"
      - "9195:9195"
    environment:
      OTEL_SERVICE_NAME: connector-2
      OTEL_TRACES_EXPORTER: jaeger
      OTEL_JAVAAGENT_EXTENSIONS: opentelemetry-exporter-jaeger.jar
      OTEL_EXPORTER_JAEGER_ENDPOINT: http://jaeger:14250
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318
      OTEL_LOGS_EXPORTER: none
      EDC_BLOCKCHAIN_INTERFACE_URL: "http://edc-interface-2:3000"
      IDS_WEBHOOK_ADDRESS: "http://connector-2:9292"
      WEB_HTTP_PORT: "9191"
      WEB_HTTP_PATH: "/api"
      WEB_HTTP_PROTOCOL_PORT: 9194
      WEB_HTTP_PROTOCOL_PATH: "/protocol"
      WEB_HTTP_MANAGEMENT_PORT: "9192"
      WEB_HTTP_MANAGEMENT_PATH: "/management"
      WEB_HTTP_CONTROL_PORT: 9193
      WEB_HTTP_CONTROL_PATH: "/control"
      WEB_HTTP_PUBLIC_PORT: 9195
      WEB_HTTP_PUBLIC_PATH: "/public"
      EDC_API_AUTH_KEY: "password"
      EDC_WEB_REST_CORS_ENABLED: "true"
      EDC_WEB_REST_CORS_HEADERS: "*"
      EDC_WEB_REST_CORS_ORIGINS: "*"
      EDC_WEB_REST_CORS_METHODS: "GET, POST, DELETE, PUT, OPTIONS"
      EDC_RECEIVER_HTTP_ENDPOINT: "http://http-push-backend-services:4000/receiver/urn:connector:provider/callback"
      EDC_DATAPLACE_TOKEN_VALIDATION_ENDPOINT: "http://connector-2:9193/control/token"
      EDC_HOSTNAME: "connector-2"
      EDC_DSP_CALLBACK_ADDRESS: "http://connector-2:9194/protocol"
    entrypoint: java
      -javaagent:/opentelemetry-javaagent.jar
      -Djava.util.logging.config.file=/open-telemetry/resources/logging.properties
      -Dedc.fs.config=config.properties
      -Dedc.keystore=cert.pfx
      -Dedc.keystore.password=123456
      -Dedc.vault=vault.properties
      -jar app.jar
  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "16686:16686"
      - "4318:4318"

  prometheus:
    image: prom/prometheus:v2.30.3
    volumes:
      - ./prometheus/:/etc/prometheus/
    ports:
      - "9090:9090"
